show_message('Connect failed. Please try again...')
